### PR TITLE
Fix: parse -maxtxfee outside of CWallet

### LINKED ISSUE #3087: [bug] maxTxFee is not set to -maxtxfee if -disablewallet is also active
# Bug Report

**Current behavior:**
Setting `-maxtxfee=1000.00` has no effect when `-disablewallet` is also active.

**Expected behavior**
Since sendrawtransaction RPC endpoint is also affected by maxtxfee, it should take effect even when CWallet is never initialized.

**Steps to reproduce:**
1. Start dogecoind with `-maxtxfee=1000.00` and `-disablewallet`
2. Use an external wallet to create a valid batch transaction with an absolute fee > 100 DOGE
3. Send it using the sendrawtransaction RPC
4. Get the absurd-high-fee error

**Screenshots**
None

**Dogecoin Core version**
v1.14.6

**Machine specs**
- OS: Ubuntu 20.04
- CPU: AWS vCPU (EC2)
- RAM: 8GB
- Disk size: 1000GB
- Disk Type (HD/SDD): HD

**Extra information**
The only place in the source that checks the -maxtxfee runtime arg is [here](https://github.com/dogecoin/dogecoin/blob/v1.14.6/src/wallet/wallet.cpp#L3964-L3977), but at the top of the function it does an early `return true` if -disablewallet is active.

### PR DESCRIPTION
**Pull request by junderw**
Fixes #3087 

This preserves the effect of -maxtxfee even when -disablewallet is active.

### CODE REVIEW

**Comment by junderw** [comment]
Note: Bitcoin Core has since switched sendrawtransaction RPC to accept a `maxfeerate` arg instead of a maximum absolute fee, so this issue does not exist in Bitcoin Core.

**Review by ullashb — APPROVED** [review]

**Review by ullashb — APPROVED** [review]

**Review by ullashb — DISMISSED** [review]

**Review by michilumin — APPROVED** [review]
This seems completely sensible and agree that maxtxfee should be settable whether the wallet segment is in use or not. I can't think of any negatives, either, as applications using core without wallet but interfacing with RPC should at least be aware of ridiculous fees (this has been a problem in the field off and on) and have this value set.

File: src/init.cpp [hunk 1]
```diff
@@ -1016,14 +1016,33 @@ bool AppInitParameterInteraction()
...
             return InitError(AmountErrMsg("minrelaytxfee", GetArg("-minrelaytxfee", "")));
-        // High fee check is done afterward in CWallet::ParameterInteraction()
         ::minRelayTxFeeRate = CFeeRate(n);
     } else if (incrementalRelayFee > ::minRelayTxFeeRate) {
         // Allow only setting incrementalRelayFee to control both
         ::minRelayTxFeeRate = incrementalRelayFee;
         LogPrintf("Increasing minrelaytxfee to %s to match incrementalrelayfee\n",::minRelayTxFeeRate.ToString());
     }
 
+    // This is the maximum absolute fee (in COIN, not satoshis)
```
Comment (chromatic) [inline src/init.cpp:1026]: Tiny nit: would this comment be better with "koinu" instead of "satoshis"?

Comment (patricklodder) [reply src/init.cpp:1026]: For now I'd not make this blocking because, for example:

```console
$ grep -rn satoshi src/validation*
src/validation.h:62://! Discourage users to set fees higher than this amount (in satoshis) per kB
src/validation.h:68://! -maxtxfee will warn if called with a higher fee than this amount (in satoshis)
src/validation.h:187:/** Absolute maximum transaction fee (in satoshis) used by wallet and mempool (rejects high fee in sendrawtransaction) */
```

Let's fix that for 1.21 the moment we start with "branding"?

Comment (chromatic) [reply src/init.cpp:1026]: That plan makes sense to me.

**Review by chromatic — APPROVED** [review]
Rebased on 1.14.7-dev to pick up the OpenSSL 3.x changes. ACK; works great on 64-bit x86 Linux.
